apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kubia-ingress
spec:
  ingressClassName: nginx-example
  rules:
  - host: "kubia.example.com"
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: kubia-nodeport
            port:
              number: 80
